apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: <enter-your-google-id-here>
  MONGODB_URI: <enter-your-mongodb-uri-here>
  NEXTAUTH_URL: <enter-your-nextauth-url-here>
  MONGO_INITDB_ROOT_USERNAME: <enter-your-mongo-username-here>
