apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-headers
  namespace: gemini-namespace
data:
  X-Forwarded-Host: "$host"
  X-Forwarded-Proto: "$scheme"
  X-Forwarded-For: "$proxy_add_x_forwarded_for"