apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: <enter-your-google-secret-here>
  NEXTAUTH_SECRET: <enter-your-nextauth-secret-here>
  NEXT_PUBLIC_API_KEY: <enter-your-next-public-api-key-here>
  MONGO_INITDB_ROOT_PASSWORD: <enter-your-mongo-init-password-here>